# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: functionInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='functionInfo.proto',
  package='perftools.symbols',
  syntax='proto3',
  serialized_pb=_b('\n\x12\x66unctionInfo.proto\x12\x11perftools.symbols\"\xc3\x02\n\x0c\x46unctionInfo\x12\x12\n\nfunctionId\x18\x01 \x01(\x04\x12\x14\n\x0c\x66unctionName\x18\x02 \x01(\t\x12-\n\x08\x63odeInfo\x18\x03 \x01(\x0b\x32\x1b.perftools.symbols.CodeInfo\x12\x39\n\x0esourceFileInfo\x18\x04 \x01(\x0b\x32!.perftools.symbols.SourceFileInfo\x12\x31\n\nmoduleInfo\x18\x05 \x01(\x0b\x32\x1d.perftools.symbols.ModuleInfo\x12\x41\n\x12lineNumbermappings\x18\x06 \x01(\x0b\x32%.perftools.symbols.LineNumberMappings\x12)\n\x06timing\x18\x07 \x01(\x0b\x32\x19.perftools.symbols.Timing\">\n\x08\x43odeInfo\x12\x32\n\x0b\x63odeRegions\x18\x01 \x03(\x0b\x32\x1d.perftools.symbols.CodeRegion\"/\n\nCodeRegion\x12\x11\n\tstartAddr\x18\x01 \x01(\x04\x12\x0e\n\x06\x62uffer\x18\x02 \x01(\x0c\"(\n\x0eSourceFileInfo\x12\x16\n\x0esourceFileName\x18\x01 \x01(\t\" \n\nModuleInfo\x12\x12\n\nmoduleName\x18\x01 \x01(\t\"V\n\x12LineNumberMappings\x12@\n\x11nativeToSourceMap\x18\x01 \x03(\x0b\x32%.perftools.symbols.LineNumberMapEntry\"P\n\x12LineNumberMapEntry\x12\x13\n\x0bstartOffset\x18\x01 \x01(\r\x12\x11\n\tendOffset\x18\x02 \x01(\r\x12\x12\n\nlineNumber\x18\x03 \x01(\r\"\x1a\n\x06Timing\x12\x10\n\x08loadTime\x18\x01 \x01(\x03\"W\n\x07Mapping\x12\r\n\x05Start\x18\x01 \x01(\x04\x12\r\n\x05Limit\x18\x02 \x01(\x04\x12\x0e\n\x06Offset\x18\x03 \x01(\x04\x12\x0c\n\x04\x46ile\x18\x04 \x01(\t\x12\x10\n\x08loadTime\x18\x05 \x01(\x03\x62\x06proto3')
)




_FUNCTIONINFO = _descriptor.Descriptor(
  name='FunctionInfo',
  full_name='perftools.symbols.FunctionInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='functionId', full_name='perftools.symbols.FunctionInfo.functionId', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='functionName', full_name='perftools.symbols.FunctionInfo.functionName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='codeInfo', full_name='perftools.symbols.FunctionInfo.codeInfo', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sourceFileInfo', full_name='perftools.symbols.FunctionInfo.sourceFileInfo', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='moduleInfo', full_name='perftools.symbols.FunctionInfo.moduleInfo', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lineNumbermappings', full_name='perftools.symbols.FunctionInfo.lineNumbermappings', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timing', full_name='perftools.symbols.FunctionInfo.timing', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=365,
)


_CODEINFO = _descriptor.Descriptor(
  name='CodeInfo',
  full_name='perftools.symbols.CodeInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='codeRegions', full_name='perftools.symbols.CodeInfo.codeRegions', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=367,
  serialized_end=429,
)


_CODEREGION = _descriptor.Descriptor(
  name='CodeRegion',
  full_name='perftools.symbols.CodeRegion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='startAddr', full_name='perftools.symbols.CodeRegion.startAddr', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='buffer', full_name='perftools.symbols.CodeRegion.buffer', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=431,
  serialized_end=478,
)


_SOURCEFILEINFO = _descriptor.Descriptor(
  name='SourceFileInfo',
  full_name='perftools.symbols.SourceFileInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sourceFileName', full_name='perftools.symbols.SourceFileInfo.sourceFileName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=480,
  serialized_end=520,
)


_MODULEINFO = _descriptor.Descriptor(
  name='ModuleInfo',
  full_name='perftools.symbols.ModuleInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='moduleName', full_name='perftools.symbols.ModuleInfo.moduleName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=522,
  serialized_end=554,
)


_LINENUMBERMAPPINGS = _descriptor.Descriptor(
  name='LineNumberMappings',
  full_name='perftools.symbols.LineNumberMappings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nativeToSourceMap', full_name='perftools.symbols.LineNumberMappings.nativeToSourceMap', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=556,
  serialized_end=642,
)


_LINENUMBERMAPENTRY = _descriptor.Descriptor(
  name='LineNumberMapEntry',
  full_name='perftools.symbols.LineNumberMapEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='startOffset', full_name='perftools.symbols.LineNumberMapEntry.startOffset', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='endOffset', full_name='perftools.symbols.LineNumberMapEntry.endOffset', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lineNumber', full_name='perftools.symbols.LineNumberMapEntry.lineNumber', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=644,
  serialized_end=724,
)


_TIMING = _descriptor.Descriptor(
  name='Timing',
  full_name='perftools.symbols.Timing',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='loadTime', full_name='perftools.symbols.Timing.loadTime', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=726,
  serialized_end=752,
)


_MAPPING = _descriptor.Descriptor(
  name='Mapping',
  full_name='perftools.symbols.Mapping',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Start', full_name='perftools.symbols.Mapping.Start', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Limit', full_name='perftools.symbols.Mapping.Limit', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Offset', full_name='perftools.symbols.Mapping.Offset', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='File', full_name='perftools.symbols.Mapping.File', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='loadTime', full_name='perftools.symbols.Mapping.loadTime', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=754,
  serialized_end=841,
)

_FUNCTIONINFO.fields_by_name['codeInfo'].message_type = _CODEINFO
_FUNCTIONINFO.fields_by_name['sourceFileInfo'].message_type = _SOURCEFILEINFO
_FUNCTIONINFO.fields_by_name['moduleInfo'].message_type = _MODULEINFO
_FUNCTIONINFO.fields_by_name['lineNumbermappings'].message_type = _LINENUMBERMAPPINGS
_FUNCTIONINFO.fields_by_name['timing'].message_type = _TIMING
_CODEINFO.fields_by_name['codeRegions'].message_type = _CODEREGION
_LINENUMBERMAPPINGS.fields_by_name['nativeToSourceMap'].message_type = _LINENUMBERMAPENTRY
DESCRIPTOR.message_types_by_name['FunctionInfo'] = _FUNCTIONINFO
DESCRIPTOR.message_types_by_name['CodeInfo'] = _CODEINFO
DESCRIPTOR.message_types_by_name['CodeRegion'] = _CODEREGION
DESCRIPTOR.message_types_by_name['SourceFileInfo'] = _SOURCEFILEINFO
DESCRIPTOR.message_types_by_name['ModuleInfo'] = _MODULEINFO
DESCRIPTOR.message_types_by_name['LineNumberMappings'] = _LINENUMBERMAPPINGS
DESCRIPTOR.message_types_by_name['LineNumberMapEntry'] = _LINENUMBERMAPENTRY
DESCRIPTOR.message_types_by_name['Timing'] = _TIMING
DESCRIPTOR.message_types_by_name['Mapping'] = _MAPPING

FunctionInfo = _reflection.GeneratedProtocolMessageType('FunctionInfo', (_message.Message,), dict(
  DESCRIPTOR = _FUNCTIONINFO,
  __module__ = 'functionInfo_pb2'
  # @@protoc_insertion_point(class_scope:perftools.symbols.FunctionInfo)
  ))
_sym_db.RegisterMessage(FunctionInfo)

CodeInfo = _reflection.GeneratedProtocolMessageType('CodeInfo', (_message.Message,), dict(
  DESCRIPTOR = _CODEINFO,
  __module__ = 'functionInfo_pb2'
  # @@protoc_insertion_point(class_scope:perftools.symbols.CodeInfo)
  ))
_sym_db.RegisterMessage(CodeInfo)

CodeRegion = _reflection.GeneratedProtocolMessageType('CodeRegion', (_message.Message,), dict(
  DESCRIPTOR = _CODEREGION,
  __module__ = 'functionInfo_pb2'
  # @@protoc_insertion_point(class_scope:perftools.symbols.CodeRegion)
  ))
_sym_db.RegisterMessage(CodeRegion)

SourceFileInfo = _reflection.GeneratedProtocolMessageType('SourceFileInfo', (_message.Message,), dict(
  DESCRIPTOR = _SOURCEFILEINFO,
  __module__ = 'functionInfo_pb2'
  # @@protoc_insertion_point(class_scope:perftools.symbols.SourceFileInfo)
  ))
_sym_db.RegisterMessage(SourceFileInfo)

ModuleInfo = _reflection.GeneratedProtocolMessageType('ModuleInfo', (_message.Message,), dict(
  DESCRIPTOR = _MODULEINFO,
  __module__ = 'functionInfo_pb2'
  # @@protoc_insertion_point(class_scope:perftools.symbols.ModuleInfo)
  ))
_sym_db.RegisterMessage(ModuleInfo)

LineNumberMappings = _reflection.GeneratedProtocolMessageType('LineNumberMappings', (_message.Message,), dict(
  DESCRIPTOR = _LINENUMBERMAPPINGS,
  __module__ = 'functionInfo_pb2'
  # @@protoc_insertion_point(class_scope:perftools.symbols.LineNumberMappings)
  ))
_sym_db.RegisterMessage(LineNumberMappings)

LineNumberMapEntry = _reflection.GeneratedProtocolMessageType('LineNumberMapEntry', (_message.Message,), dict(
  DESCRIPTOR = _LINENUMBERMAPENTRY,
  __module__ = 'functionInfo_pb2'
  # @@protoc_insertion_point(class_scope:perftools.symbols.LineNumberMapEntry)
  ))
_sym_db.RegisterMessage(LineNumberMapEntry)

Timing = _reflection.GeneratedProtocolMessageType('Timing', (_message.Message,), dict(
  DESCRIPTOR = _TIMING,
  __module__ = 'functionInfo_pb2'
  # @@protoc_insertion_point(class_scope:perftools.symbols.Timing)
  ))
_sym_db.RegisterMessage(Timing)

Mapping = _reflection.GeneratedProtocolMessageType('Mapping', (_message.Message,), dict(
  DESCRIPTOR = _MAPPING,
  __module__ = 'functionInfo_pb2'
  # @@protoc_insertion_point(class_scope:perftools.symbols.Mapping)
  ))
_sym_db.RegisterMessage(Mapping)


# @@protoc_insertion_point(module_scope)
