# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sample_t.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sample_t.proto',
  package='perftools.samples',
  syntax='proto3',
  serialized_pb=_b('\n\x0esample_t.proto\x12\x11perftools.samples\"\xd4\x01\n\x08sample_t\x12\x12\n\nstack_size\x18\x03 \x01(\x04\x12<\n\nstack_type\x18\x04 \x01(\x0e\x32(.perftools.samples.sample_t.stack_type_t\x12\x10\n\x08\x64uration\x18\x05 \x01(\x03\x12\x11\n\ttimestamp\x18\x06 \x01(\x03\x12\x0b\n\x03tid\x18\x07 \x01(\x03\x12\x11\n\tlocations\x18\x08 \x03(\x04\"1\n\x0cstack_type_t\x12\n\n\x06native\x10\x00\x12\n\n\x06python\x10\x01\x12\t\n\x05mixed\x10\x02\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_SAMPLE_T_STACK_TYPE_T = _descriptor.EnumDescriptor(
  name='stack_type_t',
  full_name='perftools.samples.sample_t.stack_type_t',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='native', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='python', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='mixed', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=201,
  serialized_end=250,
)
_sym_db.RegisterEnumDescriptor(_SAMPLE_T_STACK_TYPE_T)


_SAMPLE_T = _descriptor.Descriptor(
  name='sample_t',
  full_name='perftools.samples.sample_t',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stack_size', full_name='perftools.samples.sample_t.stack_size', index=0,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stack_type', full_name='perftools.samples.sample_t.stack_type', index=1,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='duration', full_name='perftools.samples.sample_t.duration', index=2,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='perftools.samples.sample_t.timestamp', index=3,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tid', full_name='perftools.samples.sample_t.tid', index=4,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='locations', full_name='perftools.samples.sample_t.locations', index=5,
      number=8, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SAMPLE_T_STACK_TYPE_T,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=250,
)

_SAMPLE_T.fields_by_name['stack_type'].enum_type = _SAMPLE_T_STACK_TYPE_T
_SAMPLE_T_STACK_TYPE_T.containing_type = _SAMPLE_T
DESCRIPTOR.message_types_by_name['sample_t'] = _SAMPLE_T

sample_t = _reflection.GeneratedProtocolMessageType('sample_t', (_message.Message,), dict(
  DESCRIPTOR = _SAMPLE_T,
  __module__ = 'sample_t_pb2'
  # @@protoc_insertion_point(class_scope:perftools.samples.sample_t)
  ))
_sym_db.RegisterMessage(sample_t)


# @@protoc_insertion_point(module_scope)
