/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: functionInfo.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "functionInfo.pb-c.h"
void   perftools__symbols__function_info__init
                     (Perftools__Symbols__FunctionInfo         *message)
{
  static Perftools__Symbols__FunctionInfo init_value = PERFTOOLS__SYMBOLS__FUNCTION_INFO__INIT;
  *message = init_value;
}
size_t perftools__symbols__function_info__get_packed_size
                     (const Perftools__Symbols__FunctionInfo *message)
{
  assert(message->base.descriptor == &perftools__symbols__function_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t perftools__symbols__function_info__pack
                     (const Perftools__Symbols__FunctionInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &perftools__symbols__function_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t perftools__symbols__function_info__pack_to_buffer
                     (const Perftools__Symbols__FunctionInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &perftools__symbols__function_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Perftools__Symbols__FunctionInfo *
       perftools__symbols__function_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Perftools__Symbols__FunctionInfo *)
     protobuf_c_message_unpack (&perftools__symbols__function_info__descriptor,
                                allocator, len, data);
}
void   perftools__symbols__function_info__free_unpacked
                     (Perftools__Symbols__FunctionInfo *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &perftools__symbols__function_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   perftools__symbols__code_info__init
                     (Perftools__Symbols__CodeInfo         *message)
{
  static Perftools__Symbols__CodeInfo init_value = PERFTOOLS__SYMBOLS__CODE_INFO__INIT;
  *message = init_value;
}
size_t perftools__symbols__code_info__get_packed_size
                     (const Perftools__Symbols__CodeInfo *message)
{
  assert(message->base.descriptor == &perftools__symbols__code_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t perftools__symbols__code_info__pack
                     (const Perftools__Symbols__CodeInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &perftools__symbols__code_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t perftools__symbols__code_info__pack_to_buffer
                     (const Perftools__Symbols__CodeInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &perftools__symbols__code_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Perftools__Symbols__CodeInfo *
       perftools__symbols__code_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Perftools__Symbols__CodeInfo *)
     protobuf_c_message_unpack (&perftools__symbols__code_info__descriptor,
                                allocator, len, data);
}
void   perftools__symbols__code_info__free_unpacked
                     (Perftools__Symbols__CodeInfo *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &perftools__symbols__code_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   perftools__symbols__code_region__init
                     (Perftools__Symbols__CodeRegion         *message)
{
  static Perftools__Symbols__CodeRegion init_value = PERFTOOLS__SYMBOLS__CODE_REGION__INIT;
  *message = init_value;
}
size_t perftools__symbols__code_region__get_packed_size
                     (const Perftools__Symbols__CodeRegion *message)
{
  assert(message->base.descriptor == &perftools__symbols__code_region__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t perftools__symbols__code_region__pack
                     (const Perftools__Symbols__CodeRegion *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &perftools__symbols__code_region__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t perftools__symbols__code_region__pack_to_buffer
                     (const Perftools__Symbols__CodeRegion *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &perftools__symbols__code_region__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Perftools__Symbols__CodeRegion *
       perftools__symbols__code_region__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Perftools__Symbols__CodeRegion *)
     protobuf_c_message_unpack (&perftools__symbols__code_region__descriptor,
                                allocator, len, data);
}
void   perftools__symbols__code_region__free_unpacked
                     (Perftools__Symbols__CodeRegion *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &perftools__symbols__code_region__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   perftools__symbols__source_file_info__init
                     (Perftools__Symbols__SourceFileInfo         *message)
{
  static Perftools__Symbols__SourceFileInfo init_value = PERFTOOLS__SYMBOLS__SOURCE_FILE_INFO__INIT;
  *message = init_value;
}
size_t perftools__symbols__source_file_info__get_packed_size
                     (const Perftools__Symbols__SourceFileInfo *message)
{
  assert(message->base.descriptor == &perftools__symbols__source_file_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t perftools__symbols__source_file_info__pack
                     (const Perftools__Symbols__SourceFileInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &perftools__symbols__source_file_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t perftools__symbols__source_file_info__pack_to_buffer
                     (const Perftools__Symbols__SourceFileInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &perftools__symbols__source_file_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Perftools__Symbols__SourceFileInfo *
       perftools__symbols__source_file_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Perftools__Symbols__SourceFileInfo *)
     protobuf_c_message_unpack (&perftools__symbols__source_file_info__descriptor,
                                allocator, len, data);
}
void   perftools__symbols__source_file_info__free_unpacked
                     (Perftools__Symbols__SourceFileInfo *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &perftools__symbols__source_file_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   perftools__symbols__module_info__init
                     (Perftools__Symbols__ModuleInfo         *message)
{
  static Perftools__Symbols__ModuleInfo init_value = PERFTOOLS__SYMBOLS__MODULE_INFO__INIT;
  *message = init_value;
}
size_t perftools__symbols__module_info__get_packed_size
                     (const Perftools__Symbols__ModuleInfo *message)
{
  assert(message->base.descriptor == &perftools__symbols__module_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t perftools__symbols__module_info__pack
                     (const Perftools__Symbols__ModuleInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &perftools__symbols__module_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t perftools__symbols__module_info__pack_to_buffer
                     (const Perftools__Symbols__ModuleInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &perftools__symbols__module_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Perftools__Symbols__ModuleInfo *
       perftools__symbols__module_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Perftools__Symbols__ModuleInfo *)
     protobuf_c_message_unpack (&perftools__symbols__module_info__descriptor,
                                allocator, len, data);
}
void   perftools__symbols__module_info__free_unpacked
                     (Perftools__Symbols__ModuleInfo *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &perftools__symbols__module_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   perftools__symbols__line_number_mappings__init
                     (Perftools__Symbols__LineNumberMappings         *message)
{
  static Perftools__Symbols__LineNumberMappings init_value = PERFTOOLS__SYMBOLS__LINE_NUMBER_MAPPINGS__INIT;
  *message = init_value;
}
size_t perftools__symbols__line_number_mappings__get_packed_size
                     (const Perftools__Symbols__LineNumberMappings *message)
{
  assert(message->base.descriptor == &perftools__symbols__line_number_mappings__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t perftools__symbols__line_number_mappings__pack
                     (const Perftools__Symbols__LineNumberMappings *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &perftools__symbols__line_number_mappings__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t perftools__symbols__line_number_mappings__pack_to_buffer
                     (const Perftools__Symbols__LineNumberMappings *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &perftools__symbols__line_number_mappings__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Perftools__Symbols__LineNumberMappings *
       perftools__symbols__line_number_mappings__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Perftools__Symbols__LineNumberMappings *)
     protobuf_c_message_unpack (&perftools__symbols__line_number_mappings__descriptor,
                                allocator, len, data);
}
void   perftools__symbols__line_number_mappings__free_unpacked
                     (Perftools__Symbols__LineNumberMappings *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &perftools__symbols__line_number_mappings__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   perftools__symbols__line_number_map_entry__init
                     (Perftools__Symbols__LineNumberMapEntry         *message)
{
  static Perftools__Symbols__LineNumberMapEntry init_value = PERFTOOLS__SYMBOLS__LINE_NUMBER_MAP_ENTRY__INIT;
  *message = init_value;
}
size_t perftools__symbols__line_number_map_entry__get_packed_size
                     (const Perftools__Symbols__LineNumberMapEntry *message)
{
  assert(message->base.descriptor == &perftools__symbols__line_number_map_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t perftools__symbols__line_number_map_entry__pack
                     (const Perftools__Symbols__LineNumberMapEntry *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &perftools__symbols__line_number_map_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t perftools__symbols__line_number_map_entry__pack_to_buffer
                     (const Perftools__Symbols__LineNumberMapEntry *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &perftools__symbols__line_number_map_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Perftools__Symbols__LineNumberMapEntry *
       perftools__symbols__line_number_map_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Perftools__Symbols__LineNumberMapEntry *)
     protobuf_c_message_unpack (&perftools__symbols__line_number_map_entry__descriptor,
                                allocator, len, data);
}
void   perftools__symbols__line_number_map_entry__free_unpacked
                     (Perftools__Symbols__LineNumberMapEntry *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &perftools__symbols__line_number_map_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   perftools__symbols__timing__init
                     (Perftools__Symbols__Timing         *message)
{
  static Perftools__Symbols__Timing init_value = PERFTOOLS__SYMBOLS__TIMING__INIT;
  *message = init_value;
}
size_t perftools__symbols__timing__get_packed_size
                     (const Perftools__Symbols__Timing *message)
{
  assert(message->base.descriptor == &perftools__symbols__timing__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t perftools__symbols__timing__pack
                     (const Perftools__Symbols__Timing *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &perftools__symbols__timing__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t perftools__symbols__timing__pack_to_buffer
                     (const Perftools__Symbols__Timing *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &perftools__symbols__timing__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Perftools__Symbols__Timing *
       perftools__symbols__timing__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Perftools__Symbols__Timing *)
     protobuf_c_message_unpack (&perftools__symbols__timing__descriptor,
                                allocator, len, data);
}
void   perftools__symbols__timing__free_unpacked
                     (Perftools__Symbols__Timing *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &perftools__symbols__timing__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   perftools__symbols__mapping__init
                     (Perftools__Symbols__Mapping         *message)
{
  static Perftools__Symbols__Mapping init_value = PERFTOOLS__SYMBOLS__MAPPING__INIT;
  *message = init_value;
}
size_t perftools__symbols__mapping__get_packed_size
                     (const Perftools__Symbols__Mapping *message)
{
  assert(message->base.descriptor == &perftools__symbols__mapping__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t perftools__symbols__mapping__pack
                     (const Perftools__Symbols__Mapping *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &perftools__symbols__mapping__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t perftools__symbols__mapping__pack_to_buffer
                     (const Perftools__Symbols__Mapping *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &perftools__symbols__mapping__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Perftools__Symbols__Mapping *
       perftools__symbols__mapping__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Perftools__Symbols__Mapping *)
     protobuf_c_message_unpack (&perftools__symbols__mapping__descriptor,
                                allocator, len, data);
}
void   perftools__symbols__mapping__free_unpacked
                     (Perftools__Symbols__Mapping *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &perftools__symbols__mapping__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor perftools__symbols__function_info__field_descriptors[7] =
{
  {
    "functionId",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Perftools__Symbols__FunctionInfo, has_functionid),
    offsetof(Perftools__Symbols__FunctionInfo, functionid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "functionName",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Perftools__Symbols__FunctionInfo, functionname),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "codeInfo",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Perftools__Symbols__FunctionInfo, codeinfo),
    &perftools__symbols__code_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sourceFileInfo",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Perftools__Symbols__FunctionInfo, sourcefileinfo),
    &perftools__symbols__source_file_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "moduleInfo",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Perftools__Symbols__FunctionInfo, moduleinfo),
    &perftools__symbols__module_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lineNumbermappings",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Perftools__Symbols__FunctionInfo, linenumbermappings),
    &perftools__symbols__line_number_mappings__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timing",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Perftools__Symbols__FunctionInfo, timing),
    &perftools__symbols__timing__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned perftools__symbols__function_info__field_indices_by_name[] = {
  2,   /* field[2] = codeInfo */
  0,   /* field[0] = functionId */
  1,   /* field[1] = functionName */
  5,   /* field[5] = lineNumbermappings */
  4,   /* field[4] = moduleInfo */
  3,   /* field[3] = sourceFileInfo */
  6,   /* field[6] = timing */
};
static const ProtobufCIntRange perftools__symbols__function_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor perftools__symbols__function_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "perftools.symbols.FunctionInfo",
  "FunctionInfo",
  "Perftools__Symbols__FunctionInfo",
  "perftools.symbols",
  sizeof(Perftools__Symbols__FunctionInfo),
  7,
  perftools__symbols__function_info__field_descriptors,
  perftools__symbols__function_info__field_indices_by_name,
  1,  perftools__symbols__function_info__number_ranges,
  (ProtobufCMessageInit) perftools__symbols__function_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor perftools__symbols__code_info__field_descriptors[1] =
{
  {
    "codeRegions",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Perftools__Symbols__CodeInfo, n_coderegions),
    offsetof(Perftools__Symbols__CodeInfo, coderegions),
    &perftools__symbols__code_region__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned perftools__symbols__code_info__field_indices_by_name[] = {
  0,   /* field[0] = codeRegions */
};
static const ProtobufCIntRange perftools__symbols__code_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor perftools__symbols__code_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "perftools.symbols.CodeInfo",
  "CodeInfo",
  "Perftools__Symbols__CodeInfo",
  "perftools.symbols",
  sizeof(Perftools__Symbols__CodeInfo),
  1,
  perftools__symbols__code_info__field_descriptors,
  perftools__symbols__code_info__field_indices_by_name,
  1,  perftools__symbols__code_info__number_ranges,
  (ProtobufCMessageInit) perftools__symbols__code_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor perftools__symbols__code_region__field_descriptors[2] =
{
  {
    "startAddr",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Perftools__Symbols__CodeRegion, has_startaddr),
    offsetof(Perftools__Symbols__CodeRegion, startaddr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "buffer",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Perftools__Symbols__CodeRegion, has_buffer),
    offsetof(Perftools__Symbols__CodeRegion, buffer),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned perftools__symbols__code_region__field_indices_by_name[] = {
  1,   /* field[1] = buffer */
  0,   /* field[0] = startAddr */
};
static const ProtobufCIntRange perftools__symbols__code_region__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor perftools__symbols__code_region__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "perftools.symbols.CodeRegion",
  "CodeRegion",
  "Perftools__Symbols__CodeRegion",
  "perftools.symbols",
  sizeof(Perftools__Symbols__CodeRegion),
  2,
  perftools__symbols__code_region__field_descriptors,
  perftools__symbols__code_region__field_indices_by_name,
  1,  perftools__symbols__code_region__number_ranges,
  (ProtobufCMessageInit) perftools__symbols__code_region__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor perftools__symbols__source_file_info__field_descriptors[1] =
{
  {
    "sourceFileName",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Perftools__Symbols__SourceFileInfo, sourcefilename),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned perftools__symbols__source_file_info__field_indices_by_name[] = {
  0,   /* field[0] = sourceFileName */
};
static const ProtobufCIntRange perftools__symbols__source_file_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor perftools__symbols__source_file_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "perftools.symbols.SourceFileInfo",
  "SourceFileInfo",
  "Perftools__Symbols__SourceFileInfo",
  "perftools.symbols",
  sizeof(Perftools__Symbols__SourceFileInfo),
  1,
  perftools__symbols__source_file_info__field_descriptors,
  perftools__symbols__source_file_info__field_indices_by_name,
  1,  perftools__symbols__source_file_info__number_ranges,
  (ProtobufCMessageInit) perftools__symbols__source_file_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor perftools__symbols__module_info__field_descriptors[1] =
{
  {
    "moduleName",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Perftools__Symbols__ModuleInfo, modulename),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned perftools__symbols__module_info__field_indices_by_name[] = {
  0,   /* field[0] = moduleName */
};
static const ProtobufCIntRange perftools__symbols__module_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor perftools__symbols__module_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "perftools.symbols.ModuleInfo",
  "ModuleInfo",
  "Perftools__Symbols__ModuleInfo",
  "perftools.symbols",
  sizeof(Perftools__Symbols__ModuleInfo),
  1,
  perftools__symbols__module_info__field_descriptors,
  perftools__symbols__module_info__field_indices_by_name,
  1,  perftools__symbols__module_info__number_ranges,
  (ProtobufCMessageInit) perftools__symbols__module_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor perftools__symbols__line_number_mappings__field_descriptors[1] =
{
  {
    "nativeToSourceMap",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Perftools__Symbols__LineNumberMappings, n_nativetosourcemap),
    offsetof(Perftools__Symbols__LineNumberMappings, nativetosourcemap),
    &perftools__symbols__line_number_map_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned perftools__symbols__line_number_mappings__field_indices_by_name[] = {
  0,   /* field[0] = nativeToSourceMap */
};
static const ProtobufCIntRange perftools__symbols__line_number_mappings__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor perftools__symbols__line_number_mappings__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "perftools.symbols.LineNumberMappings",
  "LineNumberMappings",
  "Perftools__Symbols__LineNumberMappings",
  "perftools.symbols",
  sizeof(Perftools__Symbols__LineNumberMappings),
  1,
  perftools__symbols__line_number_mappings__field_descriptors,
  perftools__symbols__line_number_mappings__field_indices_by_name,
  1,  perftools__symbols__line_number_mappings__number_ranges,
  (ProtobufCMessageInit) perftools__symbols__line_number_mappings__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor perftools__symbols__line_number_map_entry__field_descriptors[3] =
{
  {
    "startOffset",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Perftools__Symbols__LineNumberMapEntry, has_startoffset),
    offsetof(Perftools__Symbols__LineNumberMapEntry, startoffset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "endOffset",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Perftools__Symbols__LineNumberMapEntry, has_endoffset),
    offsetof(Perftools__Symbols__LineNumberMapEntry, endoffset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lineNumber",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Perftools__Symbols__LineNumberMapEntry, has_linenumber),
    offsetof(Perftools__Symbols__LineNumberMapEntry, linenumber),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned perftools__symbols__line_number_map_entry__field_indices_by_name[] = {
  1,   /* field[1] = endOffset */
  2,   /* field[2] = lineNumber */
  0,   /* field[0] = startOffset */
};
static const ProtobufCIntRange perftools__symbols__line_number_map_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor perftools__symbols__line_number_map_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "perftools.symbols.LineNumberMapEntry",
  "LineNumberMapEntry",
  "Perftools__Symbols__LineNumberMapEntry",
  "perftools.symbols",
  sizeof(Perftools__Symbols__LineNumberMapEntry),
  3,
  perftools__symbols__line_number_map_entry__field_descriptors,
  perftools__symbols__line_number_map_entry__field_indices_by_name,
  1,  perftools__symbols__line_number_map_entry__number_ranges,
  (ProtobufCMessageInit) perftools__symbols__line_number_map_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor perftools__symbols__timing__field_descriptors[1] =
{
  {
    "loadTime",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Perftools__Symbols__Timing, has_loadtime),
    offsetof(Perftools__Symbols__Timing, loadtime),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned perftools__symbols__timing__field_indices_by_name[] = {
  0,   /* field[0] = loadTime */
};
static const ProtobufCIntRange perftools__symbols__timing__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor perftools__symbols__timing__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "perftools.symbols.Timing",
  "Timing",
  "Perftools__Symbols__Timing",
  "perftools.symbols",
  sizeof(Perftools__Symbols__Timing),
  1,
  perftools__symbols__timing__field_descriptors,
  perftools__symbols__timing__field_indices_by_name,
  1,  perftools__symbols__timing__number_ranges,
  (ProtobufCMessageInit) perftools__symbols__timing__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor perftools__symbols__mapping__field_descriptors[5] =
{
  {
    "Start",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Perftools__Symbols__Mapping, has_start),
    offsetof(Perftools__Symbols__Mapping, start),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Limit",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Perftools__Symbols__Mapping, has_limit),
    offsetof(Perftools__Symbols__Mapping, limit),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Offset",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Perftools__Symbols__Mapping, has_offset),
    offsetof(Perftools__Symbols__Mapping, offset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "File",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Perftools__Symbols__Mapping, file),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "loadTime",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Perftools__Symbols__Mapping, has_loadtime),
    offsetof(Perftools__Symbols__Mapping, loadtime),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned perftools__symbols__mapping__field_indices_by_name[] = {
  3,   /* field[3] = File */
  1,   /* field[1] = Limit */
  2,   /* field[2] = Offset */
  0,   /* field[0] = Start */
  4,   /* field[4] = loadTime */
};
static const ProtobufCIntRange perftools__symbols__mapping__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor perftools__symbols__mapping__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "perftools.symbols.Mapping",
  "Mapping",
  "Perftools__Symbols__Mapping",
  "perftools.symbols",
  sizeof(Perftools__Symbols__Mapping),
  5,
  perftools__symbols__mapping__field_descriptors,
  perftools__symbols__mapping__field_indices_by_name,
  1,  perftools__symbols__mapping__number_ranges,
  (ProtobufCMessageInit) perftools__symbols__mapping__init,
  NULL,NULL,NULL    /* reserved[123] */
};
