/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: profile.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "profile.pb-c.h"
void   perftools__profiles__profile__init
                     (Perftools__Profiles__Profile         *message)
{
  static Perftools__Profiles__Profile init_value = PERFTOOLS__PROFILES__PROFILE__INIT;
  *message = init_value;
}
size_t perftools__profiles__profile__get_packed_size
                     (const Perftools__Profiles__Profile *message)
{
  assert(message->base.descriptor == &perftools__profiles__profile__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t perftools__profiles__profile__pack
                     (const Perftools__Profiles__Profile *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &perftools__profiles__profile__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t perftools__profiles__profile__pack_to_buffer
                     (const Perftools__Profiles__Profile *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &perftools__profiles__profile__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Perftools__Profiles__Profile *
       perftools__profiles__profile__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Perftools__Profiles__Profile *)
     protobuf_c_message_unpack (&perftools__profiles__profile__descriptor,
                                allocator, len, data);
}
void   perftools__profiles__profile__free_unpacked
                     (Perftools__Profiles__Profile *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &perftools__profiles__profile__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   perftools__profiles__value_type__init
                     (Perftools__Profiles__ValueType         *message)
{
  static Perftools__Profiles__ValueType init_value = PERFTOOLS__PROFILES__VALUE_TYPE__INIT;
  *message = init_value;
}
size_t perftools__profiles__value_type__get_packed_size
                     (const Perftools__Profiles__ValueType *message)
{
  assert(message->base.descriptor == &perftools__profiles__value_type__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t perftools__profiles__value_type__pack
                     (const Perftools__Profiles__ValueType *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &perftools__profiles__value_type__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t perftools__profiles__value_type__pack_to_buffer
                     (const Perftools__Profiles__ValueType *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &perftools__profiles__value_type__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Perftools__Profiles__ValueType *
       perftools__profiles__value_type__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Perftools__Profiles__ValueType *)
     protobuf_c_message_unpack (&perftools__profiles__value_type__descriptor,
                                allocator, len, data);
}
void   perftools__profiles__value_type__free_unpacked
                     (Perftools__Profiles__ValueType *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &perftools__profiles__value_type__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   perftools__profiles__map_str_field_entry__init
                     (Perftools__Profiles__MapStrFieldEntry         *message)
{
  static Perftools__Profiles__MapStrFieldEntry init_value = PERFTOOLS__PROFILES__MAP_STR_FIELD_ENTRY__INIT;
  *message = init_value;
}
size_t perftools__profiles__map_str_field_entry__get_packed_size
                     (const Perftools__Profiles__MapStrFieldEntry *message)
{
  assert(message->base.descriptor == &perftools__profiles__map_str_field_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t perftools__profiles__map_str_field_entry__pack
                     (const Perftools__Profiles__MapStrFieldEntry *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &perftools__profiles__map_str_field_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t perftools__profiles__map_str_field_entry__pack_to_buffer
                     (const Perftools__Profiles__MapStrFieldEntry *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &perftools__profiles__map_str_field_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Perftools__Profiles__MapStrFieldEntry *
       perftools__profiles__map_str_field_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Perftools__Profiles__MapStrFieldEntry *)
     protobuf_c_message_unpack (&perftools__profiles__map_str_field_entry__descriptor,
                                allocator, len, data);
}
void   perftools__profiles__map_str_field_entry__free_unpacked
                     (Perftools__Profiles__MapStrFieldEntry *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &perftools__profiles__map_str_field_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   perftools__profiles__map_int_field_entry__init
                     (Perftools__Profiles__MapIntFieldEntry         *message)
{
  static Perftools__Profiles__MapIntFieldEntry init_value = PERFTOOLS__PROFILES__MAP_INT_FIELD_ENTRY__INIT;
  *message = init_value;
}
size_t perftools__profiles__map_int_field_entry__get_packed_size
                     (const Perftools__Profiles__MapIntFieldEntry *message)
{
  assert(message->base.descriptor == &perftools__profiles__map_int_field_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t perftools__profiles__map_int_field_entry__pack
                     (const Perftools__Profiles__MapIntFieldEntry *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &perftools__profiles__map_int_field_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t perftools__profiles__map_int_field_entry__pack_to_buffer
                     (const Perftools__Profiles__MapIntFieldEntry *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &perftools__profiles__map_int_field_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Perftools__Profiles__MapIntFieldEntry *
       perftools__profiles__map_int_field_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Perftools__Profiles__MapIntFieldEntry *)
     protobuf_c_message_unpack (&perftools__profiles__map_int_field_entry__descriptor,
                                allocator, len, data);
}
void   perftools__profiles__map_int_field_entry__free_unpacked
                     (Perftools__Profiles__MapIntFieldEntry *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &perftools__profiles__map_int_field_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   perftools__profiles__sample__init
                     (Perftools__Profiles__Sample         *message)
{
  static Perftools__Profiles__Sample init_value = PERFTOOLS__PROFILES__SAMPLE__INIT;
  *message = init_value;
}
size_t perftools__profiles__sample__get_packed_size
                     (const Perftools__Profiles__Sample *message)
{
  assert(message->base.descriptor == &perftools__profiles__sample__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t perftools__profiles__sample__pack
                     (const Perftools__Profiles__Sample *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &perftools__profiles__sample__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t perftools__profiles__sample__pack_to_buffer
                     (const Perftools__Profiles__Sample *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &perftools__profiles__sample__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Perftools__Profiles__Sample *
       perftools__profiles__sample__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Perftools__Profiles__Sample *)
     protobuf_c_message_unpack (&perftools__profiles__sample__descriptor,
                                allocator, len, data);
}
void   perftools__profiles__sample__free_unpacked
                     (Perftools__Profiles__Sample *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &perftools__profiles__sample__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   perftools__profiles__label__init
                     (Perftools__Profiles__Label         *message)
{
  static Perftools__Profiles__Label init_value = PERFTOOLS__PROFILES__LABEL__INIT;
  *message = init_value;
}
size_t perftools__profiles__label__get_packed_size
                     (const Perftools__Profiles__Label *message)
{
  assert(message->base.descriptor == &perftools__profiles__label__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t perftools__profiles__label__pack
                     (const Perftools__Profiles__Label *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &perftools__profiles__label__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t perftools__profiles__label__pack_to_buffer
                     (const Perftools__Profiles__Label *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &perftools__profiles__label__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Perftools__Profiles__Label *
       perftools__profiles__label__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Perftools__Profiles__Label *)
     protobuf_c_message_unpack (&perftools__profiles__label__descriptor,
                                allocator, len, data);
}
void   perftools__profiles__label__free_unpacked
                     (Perftools__Profiles__Label *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &perftools__profiles__label__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   perftools__profiles__mapping__init
                     (Perftools__Profiles__Mapping         *message)
{
  static Perftools__Profiles__Mapping init_value = PERFTOOLS__PROFILES__MAPPING__INIT;
  *message = init_value;
}
size_t perftools__profiles__mapping__get_packed_size
                     (const Perftools__Profiles__Mapping *message)
{
  assert(message->base.descriptor == &perftools__profiles__mapping__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t perftools__profiles__mapping__pack
                     (const Perftools__Profiles__Mapping *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &perftools__profiles__mapping__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t perftools__profiles__mapping__pack_to_buffer
                     (const Perftools__Profiles__Mapping *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &perftools__profiles__mapping__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Perftools__Profiles__Mapping *
       perftools__profiles__mapping__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Perftools__Profiles__Mapping *)
     protobuf_c_message_unpack (&perftools__profiles__mapping__descriptor,
                                allocator, len, data);
}
void   perftools__profiles__mapping__free_unpacked
                     (Perftools__Profiles__Mapping *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &perftools__profiles__mapping__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   perftools__profiles__location__init
                     (Perftools__Profiles__Location         *message)
{
  static Perftools__Profiles__Location init_value = PERFTOOLS__PROFILES__LOCATION__INIT;
  *message = init_value;
}
size_t perftools__profiles__location__get_packed_size
                     (const Perftools__Profiles__Location *message)
{
  assert(message->base.descriptor == &perftools__profiles__location__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t perftools__profiles__location__pack
                     (const Perftools__Profiles__Location *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &perftools__profiles__location__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t perftools__profiles__location__pack_to_buffer
                     (const Perftools__Profiles__Location *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &perftools__profiles__location__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Perftools__Profiles__Location *
       perftools__profiles__location__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Perftools__Profiles__Location *)
     protobuf_c_message_unpack (&perftools__profiles__location__descriptor,
                                allocator, len, data);
}
void   perftools__profiles__location__free_unpacked
                     (Perftools__Profiles__Location *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &perftools__profiles__location__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   perftools__profiles__line__init
                     (Perftools__Profiles__Line         *message)
{
  static Perftools__Profiles__Line init_value = PERFTOOLS__PROFILES__LINE__INIT;
  *message = init_value;
}
size_t perftools__profiles__line__get_packed_size
                     (const Perftools__Profiles__Line *message)
{
  assert(message->base.descriptor == &perftools__profiles__line__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t perftools__profiles__line__pack
                     (const Perftools__Profiles__Line *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &perftools__profiles__line__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t perftools__profiles__line__pack_to_buffer
                     (const Perftools__Profiles__Line *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &perftools__profiles__line__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Perftools__Profiles__Line *
       perftools__profiles__line__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Perftools__Profiles__Line *)
     protobuf_c_message_unpack (&perftools__profiles__line__descriptor,
                                allocator, len, data);
}
void   perftools__profiles__line__free_unpacked
                     (Perftools__Profiles__Line *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &perftools__profiles__line__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   perftools__profiles__function__init
                     (Perftools__Profiles__Function         *message)
{
  static Perftools__Profiles__Function init_value = PERFTOOLS__PROFILES__FUNCTION__INIT;
  *message = init_value;
}
size_t perftools__profiles__function__get_packed_size
                     (const Perftools__Profiles__Function *message)
{
  assert(message->base.descriptor == &perftools__profiles__function__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t perftools__profiles__function__pack
                     (const Perftools__Profiles__Function *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &perftools__profiles__function__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t perftools__profiles__function__pack_to_buffer
                     (const Perftools__Profiles__Function *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &perftools__profiles__function__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Perftools__Profiles__Function *
       perftools__profiles__function__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Perftools__Profiles__Function *)
     protobuf_c_message_unpack (&perftools__profiles__function__descriptor,
                                allocator, len, data);
}
void   perftools__profiles__function__free_unpacked
                     (Perftools__Profiles__Function *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &perftools__profiles__function__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor perftools__profiles__profile__field_descriptors[14] =
{
  {
    "SampleType",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Perftools__Profiles__Profile, n_sampletype),
    offsetof(Perftools__Profiles__Profile, sampletype),
    &perftools__profiles__value_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Sample",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Perftools__Profiles__Profile, n_sample),
    offsetof(Perftools__Profiles__Profile, sample),
    &perftools__profiles__sample__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Mapping",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Perftools__Profiles__Profile, n_mapping),
    offsetof(Perftools__Profiles__Profile, mapping),
    &perftools__profiles__mapping__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Location",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Perftools__Profiles__Profile, n_location),
    offsetof(Perftools__Profiles__Profile, location),
    &perftools__profiles__location__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Function",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Perftools__Profiles__Profile, n_function),
    offsetof(Perftools__Profiles__Profile, function),
    &perftools__profiles__function__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stringTable",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Perftools__Profiles__Profile, n_stringtable),
    offsetof(Perftools__Profiles__Profile, stringtable),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dropFramesX",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Perftools__Profiles__Profile, has_dropframesx),
    offsetof(Perftools__Profiles__Profile, dropframesx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "keepFramesX",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Perftools__Profiles__Profile, has_keepframesx),
    offsetof(Perftools__Profiles__Profile, keepframesx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "TimeNanos",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Perftools__Profiles__Profile, has_timenanos),
    offsetof(Perftools__Profiles__Profile, timenanos),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "DurationNanos",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Perftools__Profiles__Profile, has_durationnanos),
    offsetof(Perftools__Profiles__Profile, durationnanos),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "PeriodType",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Perftools__Profiles__Profile, periodtype),
    &perftools__profiles__value_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Period",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Perftools__Profiles__Profile, has_period),
    offsetof(Perftools__Profiles__Profile, period),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "commentX",
    13,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Perftools__Profiles__Profile, n_commentx),
    offsetof(Perftools__Profiles__Profile, commentx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "default_sample_typeX",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Perftools__Profiles__Profile, has_default_sample_typex),
    offsetof(Perftools__Profiles__Profile, default_sample_typex),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned perftools__profiles__profile__field_indices_by_name[] = {
  9,   /* field[9] = DurationNanos */
  4,   /* field[4] = Function */
  3,   /* field[3] = Location */
  2,   /* field[2] = Mapping */
  11,   /* field[11] = Period */
  10,   /* field[10] = PeriodType */
  1,   /* field[1] = Sample */
  0,   /* field[0] = SampleType */
  8,   /* field[8] = TimeNanos */
  12,   /* field[12] = commentX */
  13,   /* field[13] = default_sample_typeX */
  6,   /* field[6] = dropFramesX */
  7,   /* field[7] = keepFramesX */
  5,   /* field[5] = stringTable */
};
static const ProtobufCIntRange perftools__profiles__profile__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 14 }
};
const ProtobufCMessageDescriptor perftools__profiles__profile__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "perftools.profiles.Profile",
  "Profile",
  "Perftools__Profiles__Profile",
  "perftools.profiles",
  sizeof(Perftools__Profiles__Profile),
  14,
  perftools__profiles__profile__field_descriptors,
  perftools__profiles__profile__field_indices_by_name,
  1,  perftools__profiles__profile__number_ranges,
  (ProtobufCMessageInit) perftools__profiles__profile__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor perftools__profiles__value_type__field_descriptors[4] =
{
  {
    "typeX",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Perftools__Profiles__ValueType, has_typex),
    offsetof(Perftools__Profiles__ValueType, typex),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "unitX",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Perftools__Profiles__ValueType, has_unitx),
    offsetof(Perftools__Profiles__ValueType, unitx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Type",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Perftools__Profiles__ValueType, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Unit",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Perftools__Profiles__ValueType, unit),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned perftools__profiles__value_type__field_indices_by_name[] = {
  2,   /* field[2] = Type */
  3,   /* field[3] = Unit */
  0,   /* field[0] = typeX */
  1,   /* field[1] = unitX */
};
static const ProtobufCIntRange perftools__profiles__value_type__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor perftools__profiles__value_type__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "perftools.profiles.ValueType",
  "ValueType",
  "Perftools__Profiles__ValueType",
  "perftools.profiles",
  sizeof(Perftools__Profiles__ValueType),
  4,
  perftools__profiles__value_type__field_descriptors,
  perftools__profiles__value_type__field_indices_by_name,
  1,  perftools__profiles__value_type__number_ranges,
  (ProtobufCMessageInit) perftools__profiles__value_type__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor perftools__profiles__map_str_field_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Perftools__Profiles__MapStrFieldEntry, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Perftools__Profiles__MapStrFieldEntry, n_value),
    offsetof(Perftools__Profiles__MapStrFieldEntry, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned perftools__profiles__map_str_field_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange perftools__profiles__map_str_field_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor perftools__profiles__map_str_field_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "perftools.profiles.MapStrFieldEntry",
  "MapStrFieldEntry",
  "Perftools__Profiles__MapStrFieldEntry",
  "perftools.profiles",
  sizeof(Perftools__Profiles__MapStrFieldEntry),
  2,
  perftools__profiles__map_str_field_entry__field_descriptors,
  perftools__profiles__map_str_field_entry__field_indices_by_name,
  1,  perftools__profiles__map_str_field_entry__number_ranges,
  (ProtobufCMessageInit) perftools__profiles__map_str_field_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor perftools__profiles__map_int_field_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Perftools__Profiles__MapIntFieldEntry, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Perftools__Profiles__MapIntFieldEntry, n_value),
    offsetof(Perftools__Profiles__MapIntFieldEntry, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned perftools__profiles__map_int_field_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange perftools__profiles__map_int_field_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor perftools__profiles__map_int_field_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "perftools.profiles.MapIntFieldEntry",
  "MapIntFieldEntry",
  "Perftools__Profiles__MapIntFieldEntry",
  "perftools.profiles",
  sizeof(Perftools__Profiles__MapIntFieldEntry),
  2,
  perftools__profiles__map_int_field_entry__field_descriptors,
  perftools__profiles__map_int_field_entry__field_indices_by_name,
  1,  perftools__profiles__map_int_field_entry__number_ranges,
  (ProtobufCMessageInit) perftools__profiles__map_int_field_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor perftools__profiles__sample__field_descriptors[6] =
{
  {
    "locationIDX",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Perftools__Profiles__Sample, n_locationidx),
    offsetof(Perftools__Profiles__Sample, locationidx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Value",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Perftools__Profiles__Sample, n_value),
    offsetof(Perftools__Profiles__Sample, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "labelX",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Perftools__Profiles__Sample, n_labelx),
    offsetof(Perftools__Profiles__Sample, labelx),
    &perftools__profiles__label__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Location",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Perftools__Profiles__Sample, n_location),
    offsetof(Perftools__Profiles__Sample, location),
    &perftools__profiles__location__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Label",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Perftools__Profiles__Sample, n_label),
    offsetof(Perftools__Profiles__Sample, label),
    &perftools__profiles__map_str_field_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "NumLabel",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Perftools__Profiles__Sample, n_numlabel),
    offsetof(Perftools__Profiles__Sample, numlabel),
    &perftools__profiles__map_int_field_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned perftools__profiles__sample__field_indices_by_name[] = {
  4,   /* field[4] = Label */
  3,   /* field[3] = Location */
  5,   /* field[5] = NumLabel */
  1,   /* field[1] = Value */
  2,   /* field[2] = labelX */
  0,   /* field[0] = locationIDX */
};
static const ProtobufCIntRange perftools__profiles__sample__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor perftools__profiles__sample__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "perftools.profiles.Sample",
  "Sample",
  "Perftools__Profiles__Sample",
  "perftools.profiles",
  sizeof(Perftools__Profiles__Sample),
  6,
  perftools__profiles__sample__field_descriptors,
  perftools__profiles__sample__field_indices_by_name,
  1,  perftools__profiles__sample__number_ranges,
  (ProtobufCMessageInit) perftools__profiles__sample__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor perftools__profiles__label__field_descriptors[3] =
{
  {
    "keyX",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Perftools__Profiles__Label, has_keyx),
    offsetof(Perftools__Profiles__Label, keyx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "strX",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Perftools__Profiles__Label, has_strx),
    offsetof(Perftools__Profiles__Label, strx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "numX",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Perftools__Profiles__Label, has_numx),
    offsetof(Perftools__Profiles__Label, numx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned perftools__profiles__label__field_indices_by_name[] = {
  0,   /* field[0] = keyX */
  2,   /* field[2] = numX */
  1,   /* field[1] = strX */
};
static const ProtobufCIntRange perftools__profiles__label__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor perftools__profiles__label__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "perftools.profiles.Label",
  "Label",
  "Perftools__Profiles__Label",
  "perftools.profiles",
  sizeof(Perftools__Profiles__Label),
  3,
  perftools__profiles__label__field_descriptors,
  perftools__profiles__label__field_indices_by_name,
  1,  perftools__profiles__label__number_ranges,
  (ProtobufCMessageInit) perftools__profiles__label__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor perftools__profiles__mapping__field_descriptors[12] =
{
  {
    "ID",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Perftools__Profiles__Mapping, has_id),
    offsetof(Perftools__Profiles__Mapping, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Start",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Perftools__Profiles__Mapping, has_start),
    offsetof(Perftools__Profiles__Mapping, start),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Limit",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Perftools__Profiles__Mapping, has_limit),
    offsetof(Perftools__Profiles__Mapping, limit),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Offset",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Perftools__Profiles__Mapping, has_offset),
    offsetof(Perftools__Profiles__Mapping, offset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fileX",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Perftools__Profiles__Mapping, has_filex),
    offsetof(Perftools__Profiles__Mapping, filex),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "buildIDX",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Perftools__Profiles__Mapping, has_buildidx),
    offsetof(Perftools__Profiles__Mapping, buildidx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "HasFunctions",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Perftools__Profiles__Mapping, has_hasfunctions),
    offsetof(Perftools__Profiles__Mapping, hasfunctions),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "HasFilenames",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Perftools__Profiles__Mapping, has_hasfilenames),
    offsetof(Perftools__Profiles__Mapping, hasfilenames),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "HasLineNumbers",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Perftools__Profiles__Mapping, has_haslinenumbers),
    offsetof(Perftools__Profiles__Mapping, haslinenumbers),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "HasInlineFrames",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Perftools__Profiles__Mapping, has_hasinlineframes),
    offsetof(Perftools__Profiles__Mapping, hasinlineframes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "File",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Perftools__Profiles__Mapping, file),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "BuildID",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Perftools__Profiles__Mapping, buildid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned perftools__profiles__mapping__field_indices_by_name[] = {
  11,   /* field[11] = BuildID */
  10,   /* field[10] = File */
  7,   /* field[7] = HasFilenames */
  6,   /* field[6] = HasFunctions */
  9,   /* field[9] = HasInlineFrames */
  8,   /* field[8] = HasLineNumbers */
  0,   /* field[0] = ID */
  2,   /* field[2] = Limit */
  3,   /* field[3] = Offset */
  1,   /* field[1] = Start */
  5,   /* field[5] = buildIDX */
  4,   /* field[4] = fileX */
};
static const ProtobufCIntRange perftools__profiles__mapping__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 12 }
};
const ProtobufCMessageDescriptor perftools__profiles__mapping__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "perftools.profiles.Mapping",
  "Mapping",
  "Perftools__Profiles__Mapping",
  "perftools.profiles",
  sizeof(Perftools__Profiles__Mapping),
  12,
  perftools__profiles__mapping__field_descriptors,
  perftools__profiles__mapping__field_indices_by_name,
  1,  perftools__profiles__mapping__number_ranges,
  (ProtobufCMessageInit) perftools__profiles__mapping__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor perftools__profiles__location__field_descriptors[5] =
{
  {
    "ID",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Perftools__Profiles__Location, has_id),
    offsetof(Perftools__Profiles__Location, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mappingIDX",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Perftools__Profiles__Location, has_mappingidx),
    offsetof(Perftools__Profiles__Location, mappingidx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Address",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Perftools__Profiles__Location, has_address),
    offsetof(Perftools__Profiles__Location, address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Line",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Perftools__Profiles__Location, n_line),
    offsetof(Perftools__Profiles__Location, line),
    &perftools__profiles__line__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Mapping",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Perftools__Profiles__Location, mapping),
    &perftools__profiles__mapping__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned perftools__profiles__location__field_indices_by_name[] = {
  2,   /* field[2] = Address */
  0,   /* field[0] = ID */
  3,   /* field[3] = Line */
  4,   /* field[4] = Mapping */
  1,   /* field[1] = mappingIDX */
};
static const ProtobufCIntRange perftools__profiles__location__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor perftools__profiles__location__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "perftools.profiles.Location",
  "Location",
  "Perftools__Profiles__Location",
  "perftools.profiles",
  sizeof(Perftools__Profiles__Location),
  5,
  perftools__profiles__location__field_descriptors,
  perftools__profiles__location__field_indices_by_name,
  1,  perftools__profiles__location__number_ranges,
  (ProtobufCMessageInit) perftools__profiles__location__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor perftools__profiles__line__field_descriptors[3] =
{
  {
    "functionIDX",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Perftools__Profiles__Line, has_functionidx),
    offsetof(Perftools__Profiles__Line, functionidx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Line",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Perftools__Profiles__Line, has_line),
    offsetof(Perftools__Profiles__Line, line),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Function",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Perftools__Profiles__Line, function),
    &perftools__profiles__function__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned perftools__profiles__line__field_indices_by_name[] = {
  2,   /* field[2] = Function */
  1,   /* field[1] = Line */
  0,   /* field[0] = functionIDX */
};
static const ProtobufCIntRange perftools__profiles__line__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor perftools__profiles__line__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "perftools.profiles.Line",
  "Line",
  "Perftools__Profiles__Line",
  "perftools.profiles",
  sizeof(Perftools__Profiles__Line),
  3,
  perftools__profiles__line__field_descriptors,
  perftools__profiles__line__field_indices_by_name,
  1,  perftools__profiles__line__number_ranges,
  (ProtobufCMessageInit) perftools__profiles__line__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor perftools__profiles__function__field_descriptors[8] =
{
  {
    "ID",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Perftools__Profiles__Function, has_id),
    offsetof(Perftools__Profiles__Function, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nameX",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Perftools__Profiles__Function, has_namex),
    offsetof(Perftools__Profiles__Function, namex),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "systemNameX",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Perftools__Profiles__Function, has_systemnamex),
    offsetof(Perftools__Profiles__Function, systemnamex),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "filenameX",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Perftools__Profiles__Function, has_filenamex),
    offsetof(Perftools__Profiles__Function, filenamex),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "StartLine",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Perftools__Profiles__Function, has_startline),
    offsetof(Perftools__Profiles__Function, startline),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Name",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Perftools__Profiles__Function, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "SystemName",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Perftools__Profiles__Function, systemname),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Filename",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Perftools__Profiles__Function, filename),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned perftools__profiles__function__field_indices_by_name[] = {
  7,   /* field[7] = Filename */
  0,   /* field[0] = ID */
  5,   /* field[5] = Name */
  4,   /* field[4] = StartLine */
  6,   /* field[6] = SystemName */
  3,   /* field[3] = filenameX */
  1,   /* field[1] = nameX */
  2,   /* field[2] = systemNameX */
};
static const ProtobufCIntRange perftools__profiles__function__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor perftools__profiles__function__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "perftools.profiles.Function",
  "Function",
  "Perftools__Profiles__Function",
  "perftools.profiles",
  sizeof(Perftools__Profiles__Function),
  8,
  perftools__profiles__function__field_descriptors,
  perftools__profiles__function__field_indices_by_name,
  1,  perftools__profiles__function__number_ranges,
  (ProtobufCMessageInit) perftools__profiles__function__init,
  NULL,NULL,NULL    /* reserved[123] */
};
