/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: sample_t.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "sample_t.pb-c.h"
void   perftools__samples__sample_t__init
                     (Perftools__Samples__SampleT         *message)
{
  static Perftools__Samples__SampleT init_value = PERFTOOLS__SAMPLES__SAMPLE_T__INIT;
  *message = init_value;
}
size_t perftools__samples__sample_t__get_packed_size
                     (const Perftools__Samples__SampleT *message)
{
  assert(message->base.descriptor == &perftools__samples__sample_t__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t perftools__samples__sample_t__pack
                     (const Perftools__Samples__SampleT *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &perftools__samples__sample_t__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t perftools__samples__sample_t__pack_to_buffer
                     (const Perftools__Samples__SampleT *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &perftools__samples__sample_t__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Perftools__Samples__SampleT *
       perftools__samples__sample_t__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Perftools__Samples__SampleT *)
     protobuf_c_message_unpack (&perftools__samples__sample_t__descriptor,
                                allocator, len, data);
}
void   perftools__samples__sample_t__free_unpacked
                     (Perftools__Samples__SampleT *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &perftools__samples__sample_t__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue perftools__samples__sample_t__stack_type_t__enum_values_by_number[3] =
{
  { "native", "PERFTOOLS__SAMPLES__SAMPLE_T__STACK_TYPE_T__native", 0 },
  { "python", "PERFTOOLS__SAMPLES__SAMPLE_T__STACK_TYPE_T__python", 1 },
  { "mixed", "PERFTOOLS__SAMPLES__SAMPLE_T__STACK_TYPE_T__mixed", 2 },
};
static const ProtobufCIntRange perftools__samples__sample_t__stack_type_t__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex perftools__samples__sample_t__stack_type_t__enum_values_by_name[3] =
{
  { "mixed", 2 },
  { "native", 0 },
  { "python", 1 },
};
const ProtobufCEnumDescriptor perftools__samples__sample_t__stack_type_t__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "perftools.samples.sample_t.stack_type_t",
  "stack_type_t",
  "Perftools__Samples__SampleT__StackTypeT",
  "perftools.samples",
  3,
  perftools__samples__sample_t__stack_type_t__enum_values_by_number,
  3,
  perftools__samples__sample_t__stack_type_t__enum_values_by_name,
  1,
  perftools__samples__sample_t__stack_type_t__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor perftools__samples__sample_t__field_descriptors[6] =
{
  {
    "stack_size",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Perftools__Samples__SampleT, has_stack_size),
    offsetof(Perftools__Samples__SampleT, stack_size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stack_type",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Perftools__Samples__SampleT, has_stack_type),
    offsetof(Perftools__Samples__SampleT, stack_type),
    &perftools__samples__sample_t__stack_type_t__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "duration",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Perftools__Samples__SampleT, has_duration),
    offsetof(Perftools__Samples__SampleT, duration),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Perftools__Samples__SampleT, has_timestamp),
    offsetof(Perftools__Samples__SampleT, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tid",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Perftools__Samples__SampleT, has_tid),
    offsetof(Perftools__Samples__SampleT, tid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "locations",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Perftools__Samples__SampleT, n_locations),
    offsetof(Perftools__Samples__SampleT, locations),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned perftools__samples__sample_t__field_indices_by_name[] = {
  2,   /* field[2] = duration */
  5,   /* field[5] = locations */
  0,   /* field[0] = stack_size */
  1,   /* field[1] = stack_type */
  4,   /* field[4] = tid */
  3,   /* field[3] = timestamp */
};
static const ProtobufCIntRange perftools__samples__sample_t__number_ranges[1 + 1] =
{
  { 3, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor perftools__samples__sample_t__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "perftools.samples.sample_t",
  "SampleT",
  "Perftools__Samples__SampleT",
  "perftools.samples",
  sizeof(Perftools__Samples__SampleT),
  6,
  perftools__samples__sample_t__field_descriptors,
  perftools__samples__sample_t__field_indices_by_name,
  1,  perftools__samples__sample_t__number_ranges,
  (ProtobufCMessageInit) perftools__samples__sample_t__init,
  NULL,NULL,NULL    /* reserved[123] */
};
