/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: sample_t.proto */

#ifndef PROTOBUF_C_sample_5ft_2eproto__INCLUDED
#define PROTOBUF_C_sample_5ft_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Perftools__Samples__SampleT Perftools__Samples__SampleT;


/* --- enums --- */

typedef enum _Perftools__Samples__SampleT__StackTypeT {
  PERFTOOLS__SAMPLES__SAMPLE_T__STACK_TYPE_T__native = 0,
  PERFTOOLS__SAMPLES__SAMPLE_T__STACK_TYPE_T__python = 1,
  PERFTOOLS__SAMPLES__SAMPLE_T__STACK_TYPE_T__mixed = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(PERFTOOLS__SAMPLES__SAMPLE_T__STACK_TYPE_T)
} Perftools__Samples__SampleT__StackTypeT;

/* --- messages --- */

struct  _Perftools__Samples__SampleT
{
  ProtobufCMessage base;
  protobuf_c_boolean has_stack_size;
  uint64_t stack_size;
  protobuf_c_boolean has_stack_type;
  Perftools__Samples__SampleT__StackTypeT stack_type;
  protobuf_c_boolean has_duration;
  int64_t duration;
  protobuf_c_boolean has_timestamp;
  int64_t timestamp;
  protobuf_c_boolean has_tid;
  int64_t tid;
  size_t n_locations;
  uint64_t *locations;
};
#define PERFTOOLS__SAMPLES__SAMPLE_T__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&perftools__samples__sample_t__descriptor) \
    , 0,0, 0,0, 0,0, 0,0, 0,0, 0,NULL }


/* Perftools__Samples__SampleT methods */
void   perftools__samples__sample_t__init
                     (Perftools__Samples__SampleT         *message);
size_t perftools__samples__sample_t__get_packed_size
                     (const Perftools__Samples__SampleT   *message);
size_t perftools__samples__sample_t__pack
                     (const Perftools__Samples__SampleT   *message,
                      uint8_t             *out);
size_t perftools__samples__sample_t__pack_to_buffer
                     (const Perftools__Samples__SampleT   *message,
                      ProtobufCBuffer     *buffer);
Perftools__Samples__SampleT *
       perftools__samples__sample_t__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   perftools__samples__sample_t__free_unpacked
                     (Perftools__Samples__SampleT *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Perftools__Samples__SampleT_Closure)
                 (const Perftools__Samples__SampleT *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor perftools__samples__sample_t__descriptor;
extern const ProtobufCEnumDescriptor    perftools__samples__sample_t__stack_type_t__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_sample_5ft_2eproto__INCLUDED */
